/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoadRequestRouteImport } from './routes/load-request'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as BrokerCommissionRouteImport } from './routes/broker-commission'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as FinanceIndexRouteImport } from './routes/finance.index'
import { Route as UsersWarehousesRouteImport } from './routes/users.warehouses'
import { Route as UsersTruckOwnersRouteImport } from './routes/users.truck-owners'
import { Route as UsersCustomersRouteImport } from './routes/users.customers'
import { Route as SettingsRegionsRouteImport } from './routes/settings.regions'
import { Route as SettingsLanguagesRouteImport } from './routes/settings.languages'
import { Route as SettingsBillingRouteImport } from './routes/settings.billing'
import { Route as SettingsAdminsRouteImport } from './routes/settings.admins'
import { Route as OperationsTripsRouteImport } from './routes/operations.trips'
import { Route as OperationsLoadsRouteImport } from './routes/operations.loads'
import { Route as OperationsBidsRouteImport } from './routes/operations.bids'
import { Route as LogisticsTrainRouteImport } from './routes/logistics.train'
import { Route as LogisticsSeaRouteImport } from './routes/logistics.sea'
import { Route as LogisticsRoadRouteImport } from './routes/logistics.road'
import { Route as LogisticsAirRouteImport } from './routes/logistics.air'
import { Route as FleetVehiclesRouteImport } from './routes/fleet.vehicles'
import { Route as FleetContainersRouteImport } from './routes/fleet.containers'
import { Route as FleetBulkRouteImport } from './routes/fleet.bulk'
import { Route as FinancePayoutsRouteImport } from './routes/finance.payouts'
import { Route as FinanceGatewaysRouteImport } from './routes/finance.gateways'
import { Route as FinanceCommissionRouteImport } from './routes/finance.commission'
import { Route as ContentPagesRouteImport } from './routes/content.pages'
import { Route as ContentNotificationsRouteImport } from './routes/content.notifications'
import { Route as ContentHelpRouteImport } from './routes/content.help'
import { Route as ContentBannersRouteImport } from './routes/content.banners'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoadRequestRoute = LoadRequestRouteImport.update({
  id: '/load-request',
  path: '/load-request',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerCommissionRoute = BrokerCommissionRouteImport.update({
  id: '/broker-commission',
  path: '/broker-commission',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const UsersWarehousesRoute = UsersWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => UsersRoute,
} as any)
const UsersTruckOwnersRoute = UsersTruckOwnersRouteImport.update({
  id: '/truck-owners',
  path: '/truck-owners',
  getParentRoute: () => UsersRoute,
} as any)
const UsersCustomersRoute = UsersCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => UsersRoute,
} as any)
const SettingsRegionsRoute = SettingsRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLanguagesRoute = SettingsLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAdminsRoute = SettingsAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SettingsRoute,
} as any)
const OperationsTripsRoute = OperationsTripsRouteImport.update({
  id: '/operations/trips',
  path: '/operations/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsLoadsRoute = OperationsLoadsRouteImport.update({
  id: '/operations/loads',
  path: '/operations/loads',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsBidsRoute = OperationsBidsRouteImport.update({
  id: '/operations/bids',
  path: '/operations/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsTrainRoute = LogisticsTrainRouteImport.update({
  id: '/logistics/train',
  path: '/logistics/train',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsSeaRoute = LogisticsSeaRouteImport.update({
  id: '/logistics/sea',
  path: '/logistics/sea',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoadRoute = LogisticsRoadRouteImport.update({
  id: '/logistics/road',
  path: '/logistics/road',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsAirRoute = LogisticsAirRouteImport.update({
  id: '/logistics/air',
  path: '/logistics/air',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetVehiclesRoute = FleetVehiclesRouteImport.update({
  id: '/fleet/vehicles',
  path: '/fleet/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetContainersRoute = FleetContainersRouteImport.update({
  id: '/fleet/containers',
  path: '/fleet/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetBulkRoute = FleetBulkRouteImport.update({
  id: '/fleet/bulk',
  path: '/fleet/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancePayoutsRoute = FinancePayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceGatewaysRoute = FinanceGatewaysRouteImport.update({
  id: '/gateways',
  path: '/gateways',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCommissionRoute = FinanceCommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => FinanceRoute,
} as any)
const ContentPagesRoute = ContentPagesRouteImport.update({
  id: '/content/pages',
  path: '/content/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentNotificationsRoute = ContentNotificationsRouteImport.update({
  id: '/content/notifications',
  path: '/content/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentHelpRoute = ContentHelpRouteImport.update({
  id: '/content/help',
  path: '/content/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentBannersRoute = ContentBannersRouteImport.update({
  id: '/content/banners',
  path: '/content/banners',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents': typeof AgentsRoute
  '/bookings': typeof BookingsRoute
  '/broker-commission': typeof BrokerCommissionRoute
  '/finance': typeof FinanceRouteWithChildren
  '/load-request': typeof LoadRequestRoute
  '/login': typeof LoginRoute
  '/ports': typeof PortsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tracking': typeof TrackingRoute
  '/users': typeof UsersRouteWithChildren
  '/content/banners': typeof ContentBannersRoute
  '/content/help': typeof ContentHelpRoute
  '/content/notifications': typeof ContentNotificationsRoute
  '/content/pages': typeof ContentPagesRoute
  '/finance/commission': typeof FinanceCommissionRoute
  '/finance/gateways': typeof FinanceGatewaysRoute
  '/finance/payouts': typeof FinancePayoutsRoute
  '/fleet/bulk': typeof FleetBulkRoute
  '/fleet/containers': typeof FleetContainersRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/logistics/air': typeof LogisticsAirRoute
  '/logistics/road': typeof LogisticsRoadRoute
  '/logistics/sea': typeof LogisticsSeaRoute
  '/logistics/train': typeof LogisticsTrainRoute
  '/operations/bids': typeof OperationsBidsRoute
  '/operations/loads': typeof OperationsLoadsRoute
  '/operations/trips': typeof OperationsTripsRoute
  '/settings/admins': typeof SettingsAdminsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/languages': typeof SettingsLanguagesRoute
  '/settings/regions': typeof SettingsRegionsRoute
  '/users/customers': typeof UsersCustomersRoute
  '/users/truck-owners': typeof UsersTruckOwnersRoute
  '/users/warehouses': typeof UsersWarehousesRoute
  '/finance/': typeof FinanceIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents': typeof AgentsRoute
  '/bookings': typeof BookingsRoute
  '/broker-commission': typeof BrokerCommissionRoute
  '/load-request': typeof LoadRequestRoute
  '/login': typeof LoginRoute
  '/ports': typeof PortsRoute
  '/tracking': typeof TrackingRoute
  '/content/banners': typeof ContentBannersRoute
  '/content/help': typeof ContentHelpRoute
  '/content/notifications': typeof ContentNotificationsRoute
  '/content/pages': typeof ContentPagesRoute
  '/finance/commission': typeof FinanceCommissionRoute
  '/finance/gateways': typeof FinanceGatewaysRoute
  '/finance/payouts': typeof FinancePayoutsRoute
  '/fleet/bulk': typeof FleetBulkRoute
  '/fleet/containers': typeof FleetContainersRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/logistics/air': typeof LogisticsAirRoute
  '/logistics/road': typeof LogisticsRoadRoute
  '/logistics/sea': typeof LogisticsSeaRoute
  '/logistics/train': typeof LogisticsTrainRoute
  '/operations/bids': typeof OperationsBidsRoute
  '/operations/loads': typeof OperationsLoadsRoute
  '/operations/trips': typeof OperationsTripsRoute
  '/settings/admins': typeof SettingsAdminsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/languages': typeof SettingsLanguagesRoute
  '/settings/regions': typeof SettingsRegionsRoute
  '/users/customers': typeof UsersCustomersRoute
  '/users/truck-owners': typeof UsersTruckOwnersRoute
  '/users/warehouses': typeof UsersWarehousesRoute
  '/finance': typeof FinanceIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/agents': typeof AgentsRoute
  '/bookings': typeof BookingsRoute
  '/broker-commission': typeof BrokerCommissionRoute
  '/finance': typeof FinanceRouteWithChildren
  '/load-request': typeof LoadRequestRoute
  '/login': typeof LoginRoute
  '/ports': typeof PortsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tracking': typeof TrackingRoute
  '/users': typeof UsersRouteWithChildren
  '/content/banners': typeof ContentBannersRoute
  '/content/help': typeof ContentHelpRoute
  '/content/notifications': typeof ContentNotificationsRoute
  '/content/pages': typeof ContentPagesRoute
  '/finance/commission': typeof FinanceCommissionRoute
  '/finance/gateways': typeof FinanceGatewaysRoute
  '/finance/payouts': typeof FinancePayoutsRoute
  '/fleet/bulk': typeof FleetBulkRoute
  '/fleet/containers': typeof FleetContainersRoute
  '/fleet/vehicles': typeof FleetVehiclesRoute
  '/logistics/air': typeof LogisticsAirRoute
  '/logistics/road': typeof LogisticsRoadRoute
  '/logistics/sea': typeof LogisticsSeaRoute
  '/logistics/train': typeof LogisticsTrainRoute
  '/operations/bids': typeof OperationsBidsRoute
  '/operations/loads': typeof OperationsLoadsRoute
  '/operations/trips': typeof OperationsTripsRoute
  '/settings/admins': typeof SettingsAdminsRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/languages': typeof SettingsLanguagesRoute
  '/settings/regions': typeof SettingsRegionsRoute
  '/users/customers': typeof UsersCustomersRoute
  '/users/truck-owners': typeof UsersTruckOwnersRoute
  '/users/warehouses': typeof UsersWarehousesRoute
  '/finance/': typeof FinanceIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/agents'
    | '/bookings'
    | '/broker-commission'
    | '/finance'
    | '/load-request'
    | '/login'
    | '/ports'
    | '/settings'
    | '/tracking'
    | '/users'
    | '/content/banners'
    | '/content/help'
    | '/content/notifications'
    | '/content/pages'
    | '/finance/commission'
    | '/finance/gateways'
    | '/finance/payouts'
    | '/fleet/bulk'
    | '/fleet/containers'
    | '/fleet/vehicles'
    | '/logistics/air'
    | '/logistics/road'
    | '/logistics/sea'
    | '/logistics/train'
    | '/operations/bids'
    | '/operations/loads'
    | '/operations/trips'
    | '/settings/admins'
    | '/settings/billing'
    | '/settings/languages'
    | '/settings/regions'
    | '/users/customers'
    | '/users/truck-owners'
    | '/users/warehouses'
    | '/finance/'
    | '/settings/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/agents'
    | '/bookings'
    | '/broker-commission'
    | '/load-request'
    | '/login'
    | '/ports'
    | '/tracking'
    | '/content/banners'
    | '/content/help'
    | '/content/notifications'
    | '/content/pages'
    | '/finance/commission'
    | '/finance/gateways'
    | '/finance/payouts'
    | '/fleet/bulk'
    | '/fleet/containers'
    | '/fleet/vehicles'
    | '/logistics/air'
    | '/logistics/road'
    | '/logistics/sea'
    | '/logistics/train'
    | '/operations/bids'
    | '/operations/loads'
    | '/operations/trips'
    | '/settings/admins'
    | '/settings/billing'
    | '/settings/languages'
    | '/settings/regions'
    | '/users/customers'
    | '/users/truck-owners'
    | '/users/warehouses'
    | '/finance'
    | '/settings'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/agents'
    | '/bookings'
    | '/broker-commission'
    | '/finance'
    | '/load-request'
    | '/login'
    | '/ports'
    | '/settings'
    | '/tracking'
    | '/users'
    | '/content/banners'
    | '/content/help'
    | '/content/notifications'
    | '/content/pages'
    | '/finance/commission'
    | '/finance/gateways'
    | '/finance/payouts'
    | '/fleet/bulk'
    | '/fleet/containers'
    | '/fleet/vehicles'
    | '/logistics/air'
    | '/logistics/road'
    | '/logistics/sea'
    | '/logistics/train'
    | '/operations/bids'
    | '/operations/loads'
    | '/operations/trips'
    | '/settings/admins'
    | '/settings/billing'
    | '/settings/languages'
    | '/settings/regions'
    | '/users/customers'
    | '/users/truck-owners'
    | '/users/warehouses'
    | '/finance/'
    | '/settings/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  AgentsRoute: typeof AgentsRoute
  BookingsRoute: typeof BookingsRoute
  BrokerCommissionRoute: typeof BrokerCommissionRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  LoadRequestRoute: typeof LoadRequestRoute
  LoginRoute: typeof LoginRoute
  PortsRoute: typeof PortsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TrackingRoute: typeof TrackingRoute
  UsersRoute: typeof UsersRouteWithChildren
  ContentBannersRoute: typeof ContentBannersRoute
  ContentHelpRoute: typeof ContentHelpRoute
  ContentNotificationsRoute: typeof ContentNotificationsRoute
  ContentPagesRoute: typeof ContentPagesRoute
  FleetBulkRoute: typeof FleetBulkRoute
  FleetContainersRoute: typeof FleetContainersRoute
  FleetVehiclesRoute: typeof FleetVehiclesRoute
  LogisticsAirRoute: typeof LogisticsAirRoute
  LogisticsRoadRoute: typeof LogisticsRoadRoute
  LogisticsSeaRoute: typeof LogisticsSeaRoute
  LogisticsTrainRoute: typeof LogisticsTrainRoute
  OperationsBidsRoute: typeof OperationsBidsRoute
  OperationsLoadsRoute: typeof OperationsLoadsRoute
  OperationsTripsRoute: typeof OperationsTripsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/load-request': {
      id: '/load-request'
      path: '/load-request'
      fullPath: '/load-request'
      preLoaderRoute: typeof LoadRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker-commission': {
      id: '/broker-commission'
      path: '/broker-commission'
      fullPath: '/broker-commission'
      preLoaderRoute: typeof BrokerCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/users/warehouses': {
      id: '/users/warehouses'
      path: '/warehouses'
      fullPath: '/users/warehouses'
      preLoaderRoute: typeof UsersWarehousesRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/truck-owners': {
      id: '/users/truck-owners'
      path: '/truck-owners'
      fullPath: '/users/truck-owners'
      preLoaderRoute: typeof UsersTruckOwnersRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/customers': {
      id: '/users/customers'
      path: '/customers'
      fullPath: '/users/customers'
      preLoaderRoute: typeof UsersCustomersRouteImport
      parentRoute: typeof UsersRoute
    }
    '/settings/regions': {
      id: '/settings/regions'
      path: '/regions'
      fullPath: '/settings/regions'
      preLoaderRoute: typeof SettingsRegionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/languages': {
      id: '/settings/languages'
      path: '/languages'
      fullPath: '/settings/languages'
      preLoaderRoute: typeof SettingsLanguagesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/admins': {
      id: '/settings/admins'
      path: '/admins'
      fullPath: '/settings/admins'
      preLoaderRoute: typeof SettingsAdminsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/operations/trips': {
      id: '/operations/trips'
      path: '/operations/trips'
      fullPath: '/operations/trips'
      preLoaderRoute: typeof OperationsTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/loads': {
      id: '/operations/loads'
      path: '/operations/loads'
      fullPath: '/operations/loads'
      preLoaderRoute: typeof OperationsLoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations/bids': {
      id: '/operations/bids'
      path: '/operations/bids'
      fullPath: '/operations/bids'
      preLoaderRoute: typeof OperationsBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/train': {
      id: '/logistics/train'
      path: '/logistics/train'
      fullPath: '/logistics/train'
      preLoaderRoute: typeof LogisticsTrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/sea': {
      id: '/logistics/sea'
      path: '/logistics/sea'
      fullPath: '/logistics/sea'
      preLoaderRoute: typeof LogisticsSeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/road': {
      id: '/logistics/road'
      path: '/logistics/road'
      fullPath: '/logistics/road'
      preLoaderRoute: typeof LogisticsRoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics/air': {
      id: '/logistics/air'
      path: '/logistics/air'
      fullPath: '/logistics/air'
      preLoaderRoute: typeof LogisticsAirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/vehicles': {
      id: '/fleet/vehicles'
      path: '/fleet/vehicles'
      fullPath: '/fleet/vehicles'
      preLoaderRoute: typeof FleetVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/containers': {
      id: '/fleet/containers'
      path: '/fleet/containers'
      fullPath: '/fleet/containers'
      preLoaderRoute: typeof FleetContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/bulk': {
      id: '/fleet/bulk'
      path: '/fleet/bulk'
      fullPath: '/fleet/bulk'
      preLoaderRoute: typeof FleetBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/payouts': {
      id: '/finance/payouts'
      path: '/payouts'
      fullPath: '/finance/payouts'
      preLoaderRoute: typeof FinancePayoutsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/gateways': {
      id: '/finance/gateways'
      path: '/gateways'
      fullPath: '/finance/gateways'
      preLoaderRoute: typeof FinanceGatewaysRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/commission': {
      id: '/finance/commission'
      path: '/commission'
      fullPath: '/finance/commission'
      preLoaderRoute: typeof FinanceCommissionRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/content/pages': {
      id: '/content/pages'
      path: '/content/pages'
      fullPath: '/content/pages'
      preLoaderRoute: typeof ContentPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/notifications': {
      id: '/content/notifications'
      path: '/content/notifications'
      fullPath: '/content/notifications'
      preLoaderRoute: typeof ContentNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/help': {
      id: '/content/help'
      path: '/content/help'
      fullPath: '/content/help'
      preLoaderRoute: typeof ContentHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/banners': {
      id: '/content/banners'
      path: '/content/banners'
      fullPath: '/content/banners'
      preLoaderRoute: typeof ContentBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FinanceRouteChildren {
  FinanceCommissionRoute: typeof FinanceCommissionRoute
  FinanceGatewaysRoute: typeof FinanceGatewaysRoute
  FinancePayoutsRoute: typeof FinancePayoutsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceCommissionRoute: FinanceCommissionRoute,
  FinanceGatewaysRoute: FinanceGatewaysRoute,
  FinancePayoutsRoute: FinancePayoutsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface SettingsRouteChildren {
  SettingsAdminsRoute: typeof SettingsAdminsRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsLanguagesRoute: typeof SettingsLanguagesRoute
  SettingsRegionsRoute: typeof SettingsRegionsRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAdminsRoute: SettingsAdminsRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsLanguagesRoute: SettingsLanguagesRoute,
  SettingsRegionsRoute: SettingsRegionsRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface UsersRouteChildren {
  UsersCustomersRoute: typeof UsersCustomersRoute
  UsersTruckOwnersRoute: typeof UsersTruckOwnersRoute
  UsersWarehousesRoute: typeof UsersWarehousesRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersCustomersRoute: UsersCustomersRoute,
  UsersTruckOwnersRoute: UsersTruckOwnersRoute,
  UsersWarehousesRoute: UsersWarehousesRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  AgentsRoute: AgentsRoute,
  BookingsRoute: BookingsRoute,
  BrokerCommissionRoute: BrokerCommissionRoute,
  FinanceRoute: FinanceRouteWithChildren,
  LoadRequestRoute: LoadRequestRoute,
  LoginRoute: LoginRoute,
  PortsRoute: PortsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TrackingRoute: TrackingRoute,
  UsersRoute: UsersRouteWithChildren,
  ContentBannersRoute: ContentBannersRoute,
  ContentHelpRoute: ContentHelpRoute,
  ContentNotificationsRoute: ContentNotificationsRoute,
  ContentPagesRoute: ContentPagesRoute,
  FleetBulkRoute: FleetBulkRoute,
  FleetContainersRoute: FleetContainersRoute,
  FleetVehiclesRoute: FleetVehiclesRoute,
  LogisticsAirRoute: LogisticsAirRoute,
  LogisticsRoadRoute: LogisticsRoadRoute,
  LogisticsSeaRoute: LogisticsSeaRoute,
  LogisticsTrainRoute: LogisticsTrainRoute,
  OperationsBidsRoute: OperationsBidsRoute,
  OperationsLoadsRoute: OperationsLoadsRoute,
  OperationsTripsRoute: OperationsTripsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
